version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@host.docker.internal:5432/dbname}
    restart: unless-stopped
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: 